### ISSUE TITLE
Compilation error in dependency fmtlib (error: expected unqualified-id before numeric constant)

### ISSUE THREAD

**Issue by ilykos** [nghiavtr/FuSeq#1]
During 'make' step inside sailfish 0.10 an error occurs breaking the installation script.

Ubuntu 18.04 / FuSeq 1.1.0

```
/home/<user>/Tools/fuseq/FuSeq-1.1.0/sailfish-0.10.0/include/spdlog/details/format.h:2056:24: error: expected unqualified-id before numeric constant
         const unsigned CHAR_WIDTH = 1;
                        ^~~~~~~~~~
```

The fix of spdlog is described here:
[https://github.com/fmtlib/fmt/commit/abbefd71666055daac9e14e78262620f9e845850](https://github.com/fmtlib/fmt/commit/abbefd71666055daac9e14e78262620f9e845850)

Bundling a more recent version of fmtlib/spdlog/sailfish will probably solve the problem.

**Comment by nghiavtr** [comment]
Dear ilykos,

Many thanks for your report and solution about the error of FuSeq during installation from source using Ubuntu 18.04.

Since I was successful with other versions of Linux (e.g., Ubuntu 16.04 and Centos 3.10 ), so I think it is likely that the error wass due to the Linux OS version rather than the Sailfish's codes.

For using the binary version of FuSeq in Ubuntu 18, as my experiment, it is still ok; but similarly to Ubuntu 16, it still needs to remove librt.so.1 from folder "linux/lib".

Best,
Nghia
