### ISSUE TITLE
library type specification UN

### ISSUE THREAD

**Issue by gudeqing** [nghiavtr/FuSeq#2]
hi，
 It seems that library type specification is not correct as I got
Exception: [unknown library format string : UN]

**Comment by nghiavtr** [comment]
Hello,
Thank you for using FuSeq.

It is a bit strange because "UN" is the default setting of FuSeq. Can you give more details the issue you got?

Best,
Nghia

**Comment by gudeqing** [comment]
hi, Nghia,
I can excute the following comand. I guess IU means unstranded lib instead, am I right ? And '-l' is a mandatory argument !
```
FuSeq -o quasiMap -l IU --biasCorrect -i TxIndexer_idx -1 $1 -2 $2 -p 8 -g Homo_sapiens.GRCh37.75.gtf
```

**Comment by nghiavtr** [comment]
I see, so you concern about the library type at this step.

You are right, IU means unstranded library in the mapping process and it is a mandatory argument, and should not be changed.

The control of library type for fusion detection is set in the params.txt, please edit the parameters in that file when necessary,

Best,
Nghia

**Comment by gudeqing** [comment]
* Yes, thank you for your reply, and Hope you can update your document on this issue because I think 
 library type is important at quasimap step, if possible, library-type should be detected automatically.

* By the way, I appreciate your wonderful work, it is fast and easy to install and easy to use. Yet,  I hope one sample may help you to improve FuSeq,  the sample "MCF-7" is from https://chimpipe.readthedocs.io/en/latest/tutorial.html . For this sample, chimpipe and star-fusion both can detect 5 validated fusion genes, while FuSeq can only detect 3 validated ones.

Best,
gudeqing

**Comment by nghiavtr** [comment]
Hi Gudeqing,

Many thanks for your comments and suggestions to improve FuSeq.
We will consider the improvements for both documentation and codes in the next version of FuSeq
The sample is interesting and under investigation.

Best,
Nghia

**Comment by nghiavtr** [comment]
Btw, I have a quick check the validated fusions from your link for the sample and discovered that one of the reasons that FuSeq cannot detect the other fusions because two of them are too close (less than 100 000 bases (default of FuSeq) for RPS6KB1-VMP1 (74 936) and SMARCA4-CARM1 (81 642)). 

When revising two parameters in the params.txt (minGeneDist= 50000 and minJunctionDist= 50000), one fusion is added (RPS6KB1-VMP1) in the results of FuSeq. The method still cannot detect SMARCA4-CARM1, I believe it depends on the suitable parameter settings for FuSeq, but not have time for investigation.

Best,
Nghia
