### ISSUE TITLE
Split Read Processing Error

### ISSUE THREAD

**Issue by mflevine** [nghiavtr/FuSeq#6]
Hi,

While testing FuSeq on a few more samples, I ran into an issue with one of my samples. I know that this sample has 4 confident fusions but I get an error after the split read processing says that there are 0 remaining reads. I have attached the stdout and stderr. Please let me know if I should send the FeqDir.
[FUSEQ_255244_command_log.log](https://github.com/nghiavtr/FuSeq/files/3473820/FUSEQ_255244_command_log.log)
[FUSEQ_255244_command_err.log](https://github.com/nghiavtr/FuSeq/files/3473824/FUSEQ_255244_command_err.log)

Best,
Max

**Comment by mflevine** [comment]
It looks like this sample is short reads. I will explore if this because of the kmer size.

**Comment by nghiavtr** [comment]
Hi Max,

From FUSEQ_255244_command_log.log, I can see your data have 50bp read long, so it should use with kmer length of 21 to capture the split reads.

Best,
Nghia

**Comment by mflevine** [comment]
Kmer length of 21 worked great! Are SR.passed and MR.passed supposed to always add up to supportRead? For many fusions I am seeing 0 in either SR.passed or MR.passed with supportRead being higher than the non-zero value. Please see attached. Thanks!
[FUSEQ_255244_fusions.FuSeq.txt](https://github.com/nghiavtr/FuSeq/files/3478360/FUSEQ_255244_fusions.FuSeq.txt)

**Comment by nghiavtr** [comment]
The supportRead is the sum of all SR and MR reads including also SR and MR not passed very strict statistical tests and filters, thus supportRead>=SM.passed + MR.passed. 

Either SR.passed or MR.passed with zero is simply because none of the reads passed our tests/filters (might be false negatives due to too strict conditions), or sometimes the read type has no clear evidence. However, the method found high confidence in the other read type.

Best,
Nghia

**Comment by mflevine** [comment]
Thank you for the clarification!
